#' @title stanedit
#' @description
#' \code{stanedit} prepares stan model code for programmatically editing.
#'
#' @param object either a `stanmodel` object as generated by
#'   [rstan::stan_model()] or a `CmdStanModel` object as generated by
#'   [cmdstanr::cmdstan_model()], or a character vector representing model code.
#' @param filename name of a file containing model code, if `object` is not
#'   given.
#' @return A \code{{stanedit}} object containing clean model code. This will
#'   have some formatting applied to it for further processing so line numbers
#'   may not correspond to the original model, and comments will be removed.
#' @importFrom methods is
#' @importFrom utils capture.output
#' @examples
#' model_file_name <- system.file(package = "stanedit", "regression.stan")
#' reg <- stanedit(filename = model_file_name)
#' reg
#' @export
stanedit <- function(object, filename) {
  if (!missing(object) + !missing(filename) != 1) {
    stop("Exactly one of 'object' or 'filename' must be given")
  }
  if (!missing(filename)) {
    model <- readLines(filename)
  } else if (is.character(model)) {
    model <- object
  } else if (is(object, "stanmodel")) {
    model <- object@model_code
  } else if (is(object, "CmdStanModel")) {
    model <- capture.output(object$format(canonicalize = TRUE))
  } else {
    stop("Unknown object type")
  }

  return(clean_model(model))
}

#' @name Extract_assign.stanedit
#' @rdname Extract_assign.stanedit
#' @title Subset and replace model lines
#' @aliases `[<-.stanedit`
#' @description
#' Extracts a subset of lines from the model and assigns new character strings.
#' @param x A stanedit
#' @param i A vector of line numbers
#' @param ... ignored
#' @return the updated \code{stanedit} object
#' @examples
#' model_file_name <- system.file(package = "rbi", "PZ.bi")
#' PZ <- stanedit(filename = model_file_name)
#' PZ[3:4] <- c("const e = 0.4", "const m_l = 0.05")
#' @export
#' @param value A vector of the same length as \code{i}, containing the
#'   replacement strings
`[<-.stanedit` <- function(x, i, ..., value) {
  model_char <- as.character(x)
  if (is.null(value)) {
    model_char <- model_char[-i]
  } else {
    model_char[i] <- value
  }
  return(clean_model(model_char))
}

#' @name Extract.stanedit
#' @rdname Extract.stanedit
#' @title Subset model lines
#' @aliases `[.stanedit`
#' @description
#' Extracts a subset of lines from the model.
#' @param x A stanedit
#' @param i A vector of line numbers
#' @param ... ignored
#' @return a character string of the extracted model lines(s)
#' @examples
#' model_file_name <- system.file(package = "rbi", "PZ.bi")
#' PZ <- stanedit(filename = model_file_name)
#' PZ[3:4]
#' @export
`[.stanedit` <- function(x, i, ...) {
  model_char <- as.character(x)
  if (missing(i)) {
    return(model_char)
  } else if (any(i >= 0)) {
    return(model_char[i])
  } else {
    return(clean_model(model_char[i]))
  }
}

#' @name Equals.stanedit
#' @rdname Equals.stanedit
#' @title Check if two models are equal
#' @aliases `==.stanedit`
#' @description
#' Ignores differences in the model name.
#' @param e1 a \code{\link{stanedit}}
#' @param e2 a \code{\link{stanedit}}
#' @param ... ignored
#' @examples
#' model_file_name <- system.file(package = "rbi", "PZ.bi")
#' PZ <- stanedit(filename = model_file_name)
#' PZ == PZ # TRUE
#' @export
#' @return TRUE or FALSE, depending on whether the models are equal or not
`==.stanedit` <- function(e1, e2, ...) { ## nolint
  return(
    length(e1) == length(e2) &&
    all(get_block(e1, "model") == get_block(e2, "model"))
  )
}

#' @name Unequals.stanedit
#' @rdname Unequals.stanedit
#' @title Check if two models are unequal
#' @aliases `!=.stanedit`
#' @description
#' Ignores differences in the model name.
#' @param e1 a \code{\link{stanedit}}
#' @param e2 a \code{\link{stanedit}}
#' @param ... ignored
#' @examples
#' model_file_name <- system.file(package = "rbi", "PZ.bi")
#' PZ <- stanedit(filename = model_file_name)
#' PZ != PZ # FALSE
#' @export
#' @return TRUE or FALSE, depending on whether the models are equal or not
`!=.stanedit` <- function(e1, e2, ...) { ## nolint
  return(!(e1 == e2))
}
